"""revision

Revision ID: c492dc6df780
Revises: 457a871767cb
Create Date: 2024-05-29 17:55:19.659502

"""
import csv
from typing import Sequence, Union
from datetime import datetime
from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import table, column


# revision identifiers, used by Alembic.
revision: str = 'c492dc6df780'
down_revision: Union[str, None] = '457a871767cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def read_csv(file_path):
    with open(file_path, mode='r', encoding='utf-8') as file:
        reader = csv.DictReader(file)
        data = [row for row in reader]
    return data

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    file_path = './data/merchants-list.csv'
    data = read_csv(file_path)
    prepared_data = [
        {
            'merchant_id': row['MerchantID'],
            'merchant_name': row['MerchantName'],
            'network': row['Network'],
            'network_id': row['NetworkID'],
            'homepage_url': row['HomepageURL'],
            'status': row['Status'],
            'merchant_about': None,
            'created_at': datetime.now(),
            'updated_at': datetime.now()
        }
        for row in data
    ]
    
    print(prepared_data)
    
    deals_table = table('deals',
        column('merchant_id', sa.Integer),
        column('merchant_name', sa.String),
        column('network', sa.String),
        column('network_id', sa.Integer),
        column('homepage_url', sa.String),
        column('status', sa.String),
        column('merchant_about', sa.String),
        column('created_at', sa.DateTime),
        column('updated_at', sa.DateTime)
    )

    op.bulk_insert(deals_table, prepared_data)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
